### ISSUE TITLE
[DJANGO] manage.py run_huey ignoring decorator @task()

### ISSUE THREAD

**Issue by diogo-oceanfone** [coleifer/huey#399]
First of all thank you for the amazing rep you got here, top notch work!

I have my django project starting up with docker-compose, I created a container as so.
```
huey:
    build: .
    restart: always
    env_file:
      - ./.env
    working_dir: /code/serviceapi
    command: bash -c "python manage.py run_huey"
    volumes:
      - .:/code # No need to re-build when code changes...
    networks:
      - cdrbackupper-proxy-net
    depends_on:
      - app
```
It works perfectly with @periodic_tasks() decorator my biggest problem is that it's not running tasks with @tasks() decorator. Here is a print of the docker-compose initializing the huey container.
![Captura de ecrã 2019-03-14, às 10 50 36](https://user-images.githubusercontent.com/48552742/54351480-78833d80-4647-11e9-8f5d-9143434b46a3.png)
Everything in green runs fine.
I'm using normal @tasks() decorator because I need this processes to run every few seconds and crontab doesn't allow this if you have a solution to use  @periodic_tasks() it's even better.

Here is the huey settings in my settings.py file.
```
HUEY = {
    'connection': {'host': 'redis', 'port': 6379},
    'always_eager': False,  # Defaults to False when running via manage.py run_huey
    'name': 'test-django',
    'consumer': {
        'loglevel': logging.ERROR if os.environ.get('DJANGO_SERVER_TYPE', '') == 'Production' else logging.DEBUG,
        'workers': 2,
    },
}
```
