### ISSUE TITLE
[Question] How to add huey to docker for Django 3.2

### ISSUE THREAD

**Issue by simkimsia** [coleifer/huey#629]
I have an existing Django 2.2 using celery 

In the .yml the settings for celery and websocket are as follows:

```
  celery:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    command: /start-celeryworker
    networks:
      - reverse_proxy
      - backend
    volumes:
      - .:/app/
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.remote_postgres
    depends_on:
      - django
      - postgres
      - redis
  celery-beat:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    command: /start-celerybeat
    networks:
      - reverse_proxy
      - backend
    volumes:
      - .:/app/
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.remote_postgres
    depends_on:
      - django
      - postgres
      - redis
  websocket:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    command: /start-asgi
    networks:
      - reverse_proxy
      - backend
    ports:
      - "8001:8001"
    volumes:
      - .:/app/
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.remote_postgres
    depends_on:
      - django
      - redis
```

Do I also need similar blocks?

the `start-celeryworker` in `celery` block is as follows:

```
#!/bin/sh

set -o errexit
set -o nounset

celery -A config.celery worker -l INFO --max-tasks-per-child=5
```

the `start-celerybeat` in `celery-beat` is as follows:

```
#!/bin/sh

set -o errexit
set -o nounset

rm -f './celerybeat.pid'
celery -A config.celery beat -l INFO
```

the `start-asgi` in `websocket` is as follows:

```
#!/bin/sh

set -o errexit
set -o nounset

daphne -b 0.0.0.0 -p 8001 websockets.asgi:application
```

I am starting a separate new Django 3.2 project and want to move away from celery and use huey. Similarly i will be using Docker.

Do I need the same 3 blocks?
