### ISSUE TITLE
Conda-forge version is quite old and doesn't auto-deploy

### ISSUE THREAD

**Issue by shreve** [coleifer/huey#665]
The version of Huey published on anaconda.org is 2.1.3 from 2019. IMO this should either be updated with the same regularity as pypi.org, or just not be available at all.

https://anaconda.org/conda-forge/huey

If using a conda environment, one can still install the pip version like the following:

```yaml
dependencies:
  - pip:
    - huey==2.4.3
```
